config/routes.rb
Rails.application.routes.draw do
  get 'boy/selfie'
  get 'boy/picture'
  get 'boy/photo'
  get 'boy/age'
  get 'boy/question_01'
  get 'boy/question_02'
  get 'boy/question_03'
  get 'boy/question_04'
  get 'boy/question_05'
  get 'boy/question_06'
  get 'boy/question_07'
  get 'boy/result'
  get 'girl/selfie'
  get 'girl/picture'
  get 'girl/photo'
  get 'girl/age'
  get 'girl/question_01'
  get 'girl/question_02'
  get 'girl/question_03'
  get 'girl/question_04'
  get 'girl/question_05'
  get 'girl/question_06'
  get 'girl/question_07'
  get 'girl/result'
  root 'principal#index'
  get 'principal/gender'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boy_controller.rb
class BoyController < ApplicationController
  def selfie
  end

  def picture
  end

  def photo
    render :layout => 'selfieBoy'
  end

  def age
  end

  def question_01
    @page_title = '¿Te brilla la piel del rostro?'
  end

  def question_02
    @page_title = '¿Como son los poros de la piel de tu rostro?'
  end

  def question_03
    @page_title = '¿Ques aspecto tiene tu piel?'
  end

  def question_04
    @page_title = '¿Sientes tirantez en la piel alrededor de ojos y bocas?'
  end

  def question_05
    @page_title = '¿Tienes granitos?'
  end

  def question_06
    @page_title = '¿Tienes pequeñas arrugas en el rostro?'
  end

  def question_07
    @page_title = '¿Suele tener manchas en el rostro?'
  end

  def result
  end
end

app/controllers/girl_controller.rb
class GirlController < ApplicationController
  def selfie
  end

  def picture
  end

  def photo
    render :layout => 'selfieGirl'
  end

  def age
  end

  def question_01
    @page_title = '¿Te brilla la piel del rostro?'
  end

  def question_02
    @page_title = '¿Como son los poros de la piel de tu rostro?'
  end

  def question_03
    @page_title = '¿Ques aspecto tiene tu piel?'
  end

  def question_04
    @page_title = '¿Sientes tirantez en la piel alrededor de ojos y bocas?'
  end

  def question_05
    @page_title = '¿Tienes granitos?'
  end

  def question_06
    @page_title = '¿Tienes pequeñas arrugas en el rostro?'
  end

  def question_07
    @page_title = '¿Suele tener manchas en el rostro?'
  end

  def result
  end
end

app/controllers/principal_controller.rb
class PrincipalController < ApplicationController
  def index
  end

  def gender
    @page_title = '¿Cúal es tu genero?'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boy_helper.rb
module BoyHelper
end

app/helpers/girl_helper.rb
module GirlHelper
end

app/helpers/principal_helper.rb
module PrincipalHelper
end

app/views/boy/age.html.erb
<h1 class="title is-size-4">
  <%= @page_title %>
</h1>

<div class="columns is-mobile">
  <div class="column is-4 is-offset-1">
    <div class="level">
      <div class="level-item has-text-centered">
        <%= link_to boy_question_01_path do %>
          <figure class="image is-128x128">
            <%= image_tag "avatars/png/age/30_menos.png", class: "is-rounded", alt:"logotipo" %>
          </figure>
        <% end %>
      </div>
    </div>
  </div>

  <div class="column is-4 is-offset-2">
    <div class="level">
      <div class="level-item has-text-centered">
        <%= link_to boy_question_01_path do %>
          <figure class="image is-128x128">
            <%= image_tag "avatars/png/age/30_44.png", class: "is-rounded", alt:"logotipo" %>
          </figure>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="columns is-mobile">
  <div class="column is-4 is-offset-1">
    <div class="level">
      <div class="level-item has-text-centered">
        <%= link_to boy_question_01_path do %>
          <figure class="image is-128x128">
            <%= image_tag "avatars/png/age/45_60.png", class: "is-rounded", alt:"logotipo" %>
          </figure>
        <% end %>
      </div>
    </div>
  </div>

  <div class="column is-4 is-offset-2">
    <div class="level">
      <div class="level-item has-text-centered">
        <%= link_to boy_question_01_path do %>
          <figure class="image is-128x128">
            <%= image_tag "avatars/png/age/61_mas.png", class: "is-rounded", alt:"logotipo" %>
          </figure>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/boy/picture.html.erb
<div class="columns is-mobile">
  <div class="column">
    <nav class="level">
      <div class="level-item has-text-centered">
        <figure class="image is-256x256">
          <%= image_tag "avatars/png/boy/pictureBoy.jpg", class: "is-rounded" %>
        </figure>
      </div>
    </nav>

    <h2 class="subtitle is-size-6">
      ¿Estas deacuerdo con esta foto?
    </h2>
    <!-- Main container -->
    <nav class="level is-mobile">
      <!-- Left side -->
      <div class="level-item has-text-centered">
        <%= link_to boy_photo_path, class: "button is-medium is-rounded" do %>
          <span class= "icon is-medium">
            <%= fa_icon "arrow-left" %>
          </span>
          <span>
            No
          </span>
        <% end %>
      </div>

      <!-- Right side -->
      <div class="level-item has-text-centered">
        <%= link_to boy_age_path, class: "button is-medium is-rounded" do %>
          <span>
            Si
          </span>
          <span class= "icon is-medium">
            <%= fa_icon "arrow-right" %>
          </span>
        <% end %>
      </div>
    </nav>

  </div>
</div>

app/views/boy/question_01.html.erb
<h1 class="title is-size-4"><%= @page_title %></h1>

<div class="columns is-mobile">
  <div class="column is-4 is-offset-1">
    <div class="level">
      <div class="level-item has-text-centered">
        <%= link_to boy_question_02_path do %>
          <figure class="image is-128x128">
            <%= image_tag "avatars/png/boy/boy_question_01/boy_question_01_answer_01.png", class: "is-rounded", alt:"logotipo" %>
          </figure>
        <% end %>
      </div>
      <h2 class="subtitle is-size-7">Si por todo el rostro</h2>
    </div>
  </div>
  <div class="column is-4 is-offset-2">
    <div class="level">
      <div class="level-item has-text-centered">
        <%= link_to boy_question_02_path do %>
          <figure class="image is-128x128">
            <%= image_tag "avatars/png/boy/boy_question_01/boy_question_01_answer_02.png", class: "is-rounded", alt:"logotipo" %>
          </figure>
        <% end %>
      </div>
      <h2 class="subtitle is-size-7">Solamente por la nariz y la frente</h2>
    </div>
  </div>
</div>

<div class="columns is-mobile">
  <div class="column is-4 is-offset-1">
    <div class="level">
      <div class="level-item has-text-centered">
        <%= link_to boy_question_02_path do %>
          <figure class="image is-128x128">
            <%= image_tag "avatars/png/boy/boy_question_01/boy_question_01_answer_04.png", class: "is-rounded", alt:"logotipo" %>
          </figure>
        <% end %>
      </div>
      <h2 class="subtitle is-size-7">No, se muestra seca y aveces se escama</h2>
    </div>
  </div>
  <div class="column is-4 is-offset-2">
    <div class="level">
      <div class="level-item has-text-centered">
        <%= link_to boy_question_02_path do %>
          <figure class="image is-128x128">
            <%= image_tag "avatars/png/boy/boy_question_01/boy_question_01_answer_03.png", class: "is-rounded", alt:"logotipo" %>
          </figure>
        <% end %>
      </div>
      <h2 class="subtitle is-size-7">No me brilla, pero tampoco esta seca</h2>
    </div>
  </div>
</div>

app/views/boy/question_02.html.erb
<h1 class="title is-size-4"><%= @page_title %></h1>

<div class="columns is-mobile">
  <div class="column is-4 is-offset-1">
    <div class="level">
      <div class="level-item has-text-centered">
        <%= link_to boy_question_03_path do %>
          <figure class="image is-128x128">
            <%= image_tag "avatars/png/boy/boy_question_02/boy_question_02_answer_04.png", class: "is-rounded", alt:"logotipo" %>
          </figure>
        <% end %>
      </div>
      <h2 class="subtitle is-size-7">Estan dilatados</h2>
    </div>
  </div>
  <div class="column is-4 is-offset-2">
    <div class="level">
      <div class="level-item has-text-centered">
        <%= link_to boy_question_03_path do %>
          <figure class="image is-128x128">
            <%= image_tag "avatars/png/boy/boy_question_02/boy_question_02_answer_03.png", class: "is-rounded", alt:"logotipo" %>
          </figure>
        <% end %>
      </div>
      <h2 class="subtitle is-size-7">Se pueden ver claramente</h2>
    </div>
  </div>
</div>

<div class="columns is-mobile">
  <div class="column is-4 is-offset-1">
    <div class="level">
      <div class="level-item has-text-centered">
        <%= link_to boy_question_03_path do %>
          <figure class="image is-128x128">
            <%= image_tag "avatars/png/boy/boy_question_02/boy_question_02_answer_02.png", class: "is-rounded", alt:"logotipo" %>
          </figure>
        <% end %>
      </div>
      <h2 class="subtitle is-size-7">Son visibles, pero pasan desapercibidos</h2>
    </div>
  </div>
  <div class="column is-4 is-offset-2">
    <div class="level">
      <div class="level-item has-text-centered">
        <%= link_to boy_question_03_path do %>
          <figure class="image is-128x128">
            <%= image_tag "avatars/png/boy/boy_question_02/boy_question_02_answer_01.png", class: "is-rounded", alt:"logotipo" %>
          </figure>
        <% end %>
      </div>
      <h2 class="subtitle is-size-7">Apenas son visibles</h2>
    </div>
  </div>
</div>

app/views/boy/question_03.html.erb
<h1 class="title is-size-4"><%= @page_title %></h1>

<div class="columns is-mobile">
  <div class="column is-4 is-offset-1">
    <div class="level">
      <div class="level-item has-text-centered">
        <%= link_to boy_question_04_path do %>
          <figure class="image is-128x128">
            <%= image_tag "avatars/png/boy/boy_question_03/boy_question_03_answer_01.png", class: "is-rounded", alt:"logotipo" %>
          </figure>
        <% end %>
      </div>
      <h2 class="subtitle is-size-7">Me brilla y parece grasa</h2>
    </div>
  </div>
  <div class="column is-4 is-offset-2">
    <div class="level">
      <div class="level-item has-text-centered">
        <%= link_to boy_question_04_path do %>
          <figure class="image is-128x128">
            <%= image_tag "avatars/png/boy/boy_question_03/boy_question_03_answer_04.png", class: "is-rounded", alt:"logotipo" %>
          </figure>
        <% end %>
      </div>
      <h2 class="subtitle is-size-7">Seca por las mejillas, pero con brillo en la nariz y frente</h2>
    </div>
  </div>
</div>

<div class="columns is-mobile">
  <div class="column is-4 is-offset-1">
    <div class="level">
      <div class="level-item has-text-centered">
        <%= link_to boy_question_04_path do %>
          <figure class="image is-128x128">
            <%= image_tag "avatars/png/boy/boy_question_03/boy_question_03_answer_03.png", class: "is-rounded", alt:"logotipo" %>
          </figure>
        <% end %>
      </div>
      <h2 class="subtitle is-size-7">Fina y seca</h2>
    </div>
  </div>

  <div class="column is-4 is-offset-2">
    <div class="level">
      <div class="level-item has-text-centered">
        <%= link_to boy_question_04_path do %>
          <figure class="image is-128x128">
            <%= image_tag "avatars/png/boy/boy_question_03/boy_question_03_answer_02.png", class: "is-rounded", alt:"logotipo" %>
          </figure>
        <% end %>
      </div>
      <h2 class="subtitle is-size-7">Fresca y tersa</h2>
    </div>
  </div>
</div>

app/views/boy/question_07.html.erb
<h1 class="title is-size-4"><%= @page_title %></h1>

<div class="columns is-mobile">
  <div class="column is-4 is-offset-1">
    <div class="level">
      <div class="level-item has-text-centered">
        <%= link_to boy_result_path do %>
          <figure class="image is-128x128">
            <%= image_tag "avatars/png/boy/boy_question_07/boy_question_07_answer_04.png", class: "is-rounded", alt:"logotipo" %>
          </figure>
        <% end %>
      </div>
      <h2 class="subtitle is-size-7">Manchas con tonalidad oscuras</h2>
    </div>
  </div>
  <div class="column is-4 is-offset-2">
    <div class="level">
      <div class="level-item has-text-centered">
        <%= link_to boy_result_path do %>
          <figure class="image is-128x128">
            <%= image_tag "avatars/png/boy/boy_question_07/boy_question_07_answer_03.png", class: "is-rounded", alt:"logotipo" %>
          </figure>
        <% end %>
      </div>
      <h2 class="subtitle is-size-7">Manchas claras en las mejillas</h2>
    </div>
  </div>
</div>

<div class="columns is-mobile">
  <div class="column is-4 is-offset-1">
    <div class="level">
      <div class="level-item has-text-centered">
        <%= link_to boy_result_path do %>
          <figure class="image is-128x128">
            <%= image_tag "avatars/png/boy/boy_question_07/boy_question_07_answer_01.png", class: "is-rounded", alt:"logotipo" %>
          </figure>
        <% end %>
      </div>
      <h2 class="subtitle is-size-7">No, pero he tenido</h2>
    </div>
  </div>
  <div class="column is-4 is-offset-2">
    <div class="level">
      <div class="level-item has-text-centered">
        <%= link_to boy_result_path do %>
          <figure class="image is-128x128">
            <%= image_tag "avatars/png/boy/boy_question_07/boy_question_07_answer_02.png", class: "is-rounded", alt:"logotipo" %>
          </figure>
        <% end %>
      </div>
      <h2 class="subtitle is-size-7">Ninguna</h2>
    </div>
  </div>
</div>

app/views/boy/result.html.erb
<div class="columns is-mobile">
            <div class="column">
              <nav class="level">
                <div class="level-item has-text-centered">
                  <figure class="image is-256x256">
                  <%= image_tag "avatars/png/boy/pictureBoy.jpg", class: "is-rounded" %>
                </figure>
                </div>
              </nav>
              <p>
                <h1 class="subtitle is-size-4">
                  Tu piel es
                </h1>
                <h1 class="title is-size-4">
                  SECA
                </h1>
              </p>

              <p>
                <h2 class="content subtitle is-size-6 has-text-justified">
                  La piel seca presenta poca elasticidad y cierta tirantez, su tacto es áspero, y le falta flexibilidad y suavidad.  La piel seca al ser tensa, fina y frágil puede llegar a producir algún tipo de descamación e irritaciones por eso requiere cuidados y productos específicos que ayuden a restablecer la barrera de la piel y que aporten la hidratación que necesita.
                </h2>
              </p>

              <p>
                <h2 class="content subtitle is-size-6 has-text-left">
                  Te recomendamos los siguientes productos:
                </h2>
                <div class="columns is-mobile">
                  <div class="column is-4 is-offset-1">
                    <div class="level">
                      <div class="level-item has-text-centered">
                        <%= link_to boy_result_path do %>
                          <figure class="image is-128x128">
                            <%= image_tag "product_01.jpg", class: "is-rounded", alt:"logotipo" %>
                          </figure>
                        <% end %>
                      </div>
                      <h2 class="subtitle is-size-7">
                        Nombre de producto
                      </h2>
                    </div>
                  </div>

                  <div class="column is-4 is-offset-2">
                    <div class="level">
                      <div class="level-item has-text-centered">
                        <%= link_to boy_result_path do %>
                          <figure class="image is-128x128">
                            <%= image_tag "product_02.jpg", class: "is-rounded", alt:"logotipo" %>
                          </figure>
                        <% end %>
                      </div>
                      <h2 class="subtitle is-size-7">
                        Nombre de producto
                      </h2>
                    </div>
                  </div>
                </div>
              </p>
              <p>
                Puedes adquirirlos con tu profesional de la estética o en nuestra tienda virtual haciendo click aqui.
              </p>
              <p>
                <a href="https://mediestetica.co/">
                  <span class="icon is-large">
                    <%= fa_icon "shopping-cart", class: "fa-3x" %>
                  </span>
                </a>
              </p>

              <br>
              <%= link_to "Repetir test", principal_gender_path, class: "button is-small is-rounded" %>
            </div>
          </div>

app/views/boy/selfie.html.erb
<h1 class="title is-size-4">
  Tomate una selfie
</h1>
<h2 class="subtitle is-size-6">
  Asegurate de tener buena iluminación
</h2>

<nav class="level">
  <div class="level-item has-text-centered">
    <figure class="image is-128x128">
      <%= image_tag "avatars/png/boy/selfieBoy.png", class: "is-rounded" %>
    </figure>
  </div>
</nav>

<h2 class="subtitle is-size-6">
  Usaremos tu foto para ayudar a determinar tu tipo de piel
</h2>

<%= link_to boy_photo_path, class: "button is-link is-medium is-rounded" do %>
  <span>
    <%= fa_icon "camera" %>
  </span>
<% end %>

app/views/girl/picture.html.erb
<div class="columns is-mobile">
  <div class="column">
    <nav class="level">
      <div class="level-item has-text-centered">
        <figure class="image is-256x256">
          <%= image_tag "avatars/png/girl/pictureGirl.jpg", class: "is-rounded" %>
        </figure>
      </div>
    </nav>

    <h2 class="subtitle is-size-6">
      ¿Estas deacuerdo con esta foto?
    </h2>
    <!-- Main container -->
    <nav class="level is-mobile">
      <!-- Left side -->
      <div class="level-item has-text-centered">
        <%= link_to girl_photo_path, class: "button is-medium is-rounded" do %>
          <span class= "icon is-medium">
            <%= fa_icon "arrow-left" %>
          </span>
          <span>
            No
          </span>
        <% end %>
      </div>

      <!-- Right side -->
      <div class="level-item has-text-centered">
        <%= link_to girl_age_path, class: "button is-medium is-rounded" do %>
          <span>
            Si
          </span>
          <span class= "icon is-medium">
            <%= fa_icon "arrow-right" %>
          </span>
        <% end %>
      </div>
    </nav>

  </div>
</div>

app/views/girl/question_07.html.erb
<h1 class="title is-size-4"><%= @page_title %></h1>

<div class="columns is-mobile">
  <div class="column is-4 is-offset-1">
    <div class="level">
      <div class="level-item has-text-centered">
        <%= link_to girl_result_path do %>
          <figure class="image is-128x128">
            <%= image_tag "avatars/png/girl/girl_question_07/girl_question_07_answer_04.png", class: "is-rounded", alt:"logotipo" %>
          </figure>
        <% end %>
      </div>
      <h2 class="subtitle is-size-7">Manchas con tonalidad oscuras</h2>
    </div>
  </div>
  <div class="column is-4 is-offset-2">
    <div class="level">
      <div class="level-item has-text-centered">
        <%= link_to girl_result_path do %>
          <figure class="image is-128x128">
            <%= image_tag "avatars/png/girl/girl_question_07/girl_question_07_answer_03.png", class: "is-rounded", alt:"logotipo" %>
          </figure>
        <% end %>
      </div>
      <h2 class="subtitle is-size-7">Manchas claras en las mejillas</h2>
    </div>
  </div>
</div>

<div class="columns is-mobile">
  <div class="column is-4 is-offset-1">
    <div class="level">
      <div class="level-item has-text-centered">
        <%= link_to girl_result_path do %>
          <figure class="image is-128x128">
            <%= image_tag "avatars/png/girl/girl_question_07/girl_question_07_answer_01.png", class: "is-rounded", alt:"logotipo" %>
          </figure>
        <% end %>
      </div>
      <h2 class="subtitle is-size-7">No, pero he tenido</h2>
    </div>
  </div>

  <div class="column is-4 is-offset-2">
    <div class="level">
      <div class="level-item has-text-centered">
        <%= link_to girl_result_path do %>
          <figure class="image is-128x128">
            <%= image_tag "avatars/png/girl/girl_question_07/girl_question_07_answer_02.png", class: "is-rounded", alt:"logotipo" %>
          </figure>
        <% end %>
      </div>
      <h2 class="subtitle is-size-7">Ninguna</h2>
    </div>
  </div>
</div>

app/views/girl/result.html.erb
<div class="columns is-mobile">
  <div class="column">
    <nav class="level">
      <div class="level-item has-text-centered">
        <figure class="image is-256x256">
        <%= image_tag "avatars/png/girl/pictureGirl.jpg", class: "is-rounded" %>
      </figure>
      </div>
    </nav>
    <p>
      <h1 class="subtitle is-size-4">
        Tu piel es
      </h1>
      <h1 class="title is-size-4">
        SECA
      </h1>
    </p>

    <p>
      <h2 class="content subtitle is-size-6 has-text-justified">
        La piel seca presenta poca elasticidad y cierta tirantez, su tacto es áspero, y le falta flexibilidad y suavidad.  La piel seca al ser tensa, fina y frágil puede llegar a producir algún tipo de descamación e irritaciones por eso requiere cuidados y productos específicos que ayuden a restablecer la barrera de la piel y que aporten la hidratación que necesita.
      </h2>
    </p>

    <p>
      <h2 class="content subtitle is-size-6 has-text-left">
        Te recomendamos los siguientes productos:
      </h2>
      <div class="columns is-mobile">
        <div class="column is-4 is-offset-1">
          <div class="level">
            <div class="level-item has-text-centered">
              <%= link_to boy_result_path do %>
                <figure class="image is-128x128">
                  <%= image_tag "product_01.jpg", class: "is-rounded", alt:"logotipo" %>
                </figure>
              <% end %>
            </div>
            <h2 class="subtitle is-size-7">
              Nombre de producto
            </h2>
          </div>
        </div>

        <div class="column is-4 is-offset-2">
          <div class="level">
            <div class="level-item has-text-centered">
              <%= link_to boy_result_path do %>
                <figure class="image is-128x128">
                  <%= image_tag "product_02.jpg", class: "is-rounded", alt:"logotipo" %>
                </figure>
              <% end %>
            </div>
            <h2 class="subtitle is-size-7">
              Nombre de producto
            </h2>
          </div>
        </div>
      </div>

    </p>
    <p>
      Puedes adquirirlos con tu profesional de la estética o en nuestra tienda virtual haciendo click aqui.
    </p>
    <p>
      <a href="https://mediestetica.co/">
        <span class="icon is-large">
          <%= fa_icon "shopping-cart", class: "fa-3x" %>
        </span>
      </a>
    </p>

    <br>
    <%= link_to "Repetir test", principal_gender_path, class: "button is-small is-rounded" %>
  </div>
</div>

app/views/girl/selfie.html.erb
<h1 class="title is-size-4">
  Tomate una selfie
</h1>
<h2 class="subtitle is-size-6">
  Asegurate de tener buena iluminación
</h2>

<nav class="level">
  <div class="level-item has-text-centered">
    <figure class="image is-128x128">
      <%= image_tag "avatars/png/girl/selfieGirl.png", class: "is-rounded" %>
    </figure>
  </div>
</nav>

<h2 class="subtitle is-size-6">
  Usaremos tu foto para ayudar a determinar tu tipo de piel
</h2>

<%= link_to girl_photo_path, class: "button is-link is-medium is-rounded" do %>
  <span>
    <%= fa_icon "camera" %>
  </span>
<% end %>

app/views/layouts/selfieBoy.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mediesteticaprototypemobile</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'favicon.png' %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class="hero is-light is-fullheight img-photo-boy">
      <!-- Hero content: will be in the middle -->
      <div class="hero-body">
        <div class="container has-text-centered">
          <%= yield %>
        </div>
      </div>

      <!-- Hero footer: will stick at the bottom -->
      <div class="hero-foot">
        <nav class="tabs is-boxed is-fullwidth">
          <div class="container">
            <ul>
              <li class="">
                <%= link_to "Reintentar", boy_selfie_path, class: "has-text-danger" %>
              </li>
              <li class="">
                <%= link_to "Aceptar", boy_picture_path, class: "has-text-danger" %>
              </li>
            </ul>
          </div>
        </nav>
      </div>
    </section>
  </body>
</html>

app/views/layouts/selfieGirl.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mediesteticaprototypemobile</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'favicon.png' %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class="hero is-light is-fullheight img-photo-girl">
      <!-- Hero content: will be in the middle -->
      <div class="hero-body">
        <div class="container has-text-centered">
          <%= yield %>
        </div>
      </div>

      <!-- Hero footer: will stick at the bottom -->
      <div class="hero-foot">
        <nav class="tabs is-boxed is-fullwidth">
          <div class="container">
            <ul>
              <li class="">
                <%= link_to "Reintentar", girl_selfie_path, class: "has-text-danger" %>
              </li>
              <li class="">
                <%= link_to "Aceptar", girl_picture_path, class: "has-text-danger" %>
              </li>
            </ul>
          </div>
        </nav>
      </div>
    </section>
  </body>
</html>

app/views/principal/gender.html.erb
<h1 class="title is-size-4">
  <%= @page_title %>
</h1>

<div class="columns is-mobile">
  <div class="column is-4 is-offset-1">
    <div class="level">
      <div class="level-item has-text-centered">
        <%= link_to girl_selfie_path do %>
          <figure class="image is-128x128">
            <%= image_tag "avatars/png/girl/avatarGirl.png", class: "is-rounded", alt:"logotipo" %>
          </figure>
        <% end %>
      </div>
      <h2 class="subtitle is-size-7">
        Femenino
      </h2>
    </div>
  </div>

  <div class="column is-4 is-offset-2">
    <div class="level">
      <div class="level-item has-text-centered">
        <%= link_to boy_selfie_path do %>
          <figure class="image is-128x128">
            <%= image_tag "avatars/png/boy/avatarBoy.png", class: "is-rounded", alt:"logotipo" %>
          </figure>
        <% end %>
      </div>
      <h2 class="subtitle is-size-7">
        Masculino
      </h2>
    </div>
  </div>
</div>

app/views/principal/index.html.erb
<div class="columns is-mobile">
  <div class="column">
    <nav class="level">
      <div class="level-item has-text-centered">
        <figure class="image is-128x128">
          <%= image_tag "logo.svg", class: "is-rounded", alt:"logotipo" %>
        </figure>
      </div>
    </nav>
    <h1 class="title is-size-4">
      ¿Quieres conocer tu tipo de piel?
    </h1>
    <%= link_to "Comencemos", principal_gender_path, class: "button is-link is-medium is-rounded" %>
  </div>
</div>